### PR TITLE
Make index macros not recreate indexes on incremental models

### PR DESCRIPTION
**Pull request by infused-kim**
If you create indexes on an incremental model like this:
```jinja
{{
    config(
        materialized='incremental',
        as_columnstore = false,
        unique_key='my_key',
	    post_hook = [
		    "{{ create_clustered_index(columns = ['my_key'], 
                                                                 unique=True) }}",
		    "{{ create_nonclustered_index(columns = ['id']) }}",
	    ]
    )
}}
```

You get this error on subsequent runs:
```shell
  ('42S11', "[42S11] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The operation failed because an index or statistics with name ‘my_table__clustered_index_on_my’_col already exists on table ‘my-db.dbt_xyz.my_table’. (1913) (SQLExecDirectW)")
```

This can be avoided by dropping the indexes in a pre-hook, but that leads to the index being recreated from scratch for all rows in the table. On a large incremental model that's probably not ideal in most cases.

This PR adds a check to the macros to only create the index if it doesn't exist yet. This way SQL server only adds the newly merged values to the index and doesn't reprocess all rows.

I don't think this would create any breaking changes for existing users of the macros. If they are already dropping indexes, it would not affect them.

And if they are using indexes on non-incremental models, then it should also not make a difference.

I have been using these macros for several months in production now and haven't had any issues.

This addresses the issue https://github.com/dbt-msft/dbt-sqlserver/issues/25 I raised about this.

### CODE REVIEW

**Comment by alittlesliceoftom** [comment]
@mikaelene I think this one should be approved, I've been using the macros (just from my local macros folder) and they work really nicely. 

Big thanks @infused-kim for raising

**Comment by mikaelene** [comment]
Great! @infused-kim , can you update the changeling as well? Adding a row of which issue it solves etc...

**Comment by visch** [comment]
Works for me

@infused-kim  

Here's an example changelog to add, I can rebase if you'd like?

**New Features**

- Adding Index Macros now check to see if the index already exists before attempting to add the index to your table

**Comment by semcha** [comment]
@swanderz Hi! What does it take to release this PR?

**Pull request merged**
